### ISSUE TITLE
How to use this function

### ISSUE THREAD

**Issue by qcjx123** [Taeyoung96/LIO-SAM-save-trajectory#1]
i try to use this function ,but i can't save the trajectory. please tell me how to use this

**Comment by Taeyoung96** [comment]
@qcjx123   
Hi, can you tell me which config file and launch file you used?

The parts below must be included in the config file.
```
  saveTrajectory: true
  saveTrajectoryResult : "/home/catkin_ws/src/result/lio-sam.txt"
```
And the `saveTrajectoryResult` should be modified and put in according to the absolute path of the repository.

**Comment by qcjx123** [comment]
Thank you，i have done this function yesterday！
